// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using XTND_Technical_Assessment.Infra;

#nullable disable

namespace XTND_Technical_Assessment.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260202173235_CreateTasksTables")]
    partial class CreateTasksTables
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("XTND_Technical_Assessment.Domain.TaskItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("TaskCreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("TaskUpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("TaskUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("TaskUserId");

                    b.ToTable("tasks", (string)null);
                });

            modelBuilder.Entity("XTND_Technical_Assessment.Domain.TaskUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.ToTable("task_users", (string)null);
                });

            modelBuilder.Entity("XTND_Technical_Assessment.Domain.TaskItem", b =>
                {
                    b.HasOne("XTND_Technical_Assessment.Domain.TaskUser", "TaskUser")
                        .WithMany("Tasks")
                        .HasForeignKey("TaskUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("TaskUser");
                });

            modelBuilder.Entity("XTND_Technical_Assessment.Domain.TaskUser", b =>
                {
                    b.Navigation("Tasks");
                });
#pragma warning restore 612, 618
        }
    }
}
