// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using XTND_Technical_Assessment.Infra;

#nullable disable

namespace XTND_Technical_Assessment.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260203212553_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("XTND_Technical_Assessment.Domain.TaskItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("TaskCreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("TaskItemStatusId")
                        .HasColumnType("integer");

                    b.Property<int>("TaskStatusId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("TaskUpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("TaskUserId")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("TaskItemStatusId");

                    b.HasIndex("TaskStatusId");

                    b.HasIndex("TaskUserId");

                    b.ToTable("tasks", (string)null);
                });

            modelBuilder.Entity("XTND_Technical_Assessment.Domain.TaskItemStatus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("task_item_statuses", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IsActive = true,
                            Name = "Backlog"
                        },
                        new
                        {
                            Id = 2,
                            IsActive = true,
                            Name = "In Progress"
                        },
                        new
                        {
                            Id = 3,
                            IsActive = true,
                            Name = "Completed"
                        });
                });

            modelBuilder.Entity("XTND_Technical_Assessment.Domain.TaskUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.ToTable("task_users", (string)null);
                });

            modelBuilder.Entity("XTND_Technical_Assessment.Domain.TaskItem", b =>
                {
                    b.HasOne("XTND_Technical_Assessment.Domain.TaskItemStatus", null)
                        .WithMany("Tasks")
                        .HasForeignKey("TaskItemStatusId");

                    b.HasOne("XTND_Technical_Assessment.Domain.TaskItemStatus", "TaskStatus")
                        .WithMany()
                        .HasForeignKey("TaskStatusId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("XTND_Technical_Assessment.Domain.TaskUser", "TaskUser")
                        .WithMany("Tasks")
                        .HasForeignKey("TaskUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("TaskStatus");

                    b.Navigation("TaskUser");
                });

            modelBuilder.Entity("XTND_Technical_Assessment.Domain.TaskItemStatus", b =>
                {
                    b.Navigation("Tasks");
                });

            modelBuilder.Entity("XTND_Technical_Assessment.Domain.TaskUser", b =>
                {
                    b.Navigation("Tasks");
                });
#pragma warning restore 612, 618
        }
    }
}
